nelmio_api_doc:
    documentation:
        # servers:
        #   - url: http://api.example.com/unsafe
        #     description: API over HTTP
        #   - url: https://api.example.com/secured
        #     description: API over HTTPS
        info:
            title: Aubesport
            description: Une API du site Aubesport
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas:
        default:
            disable_default_routes: true
