version: '3.5'

services:
    nginx:
        image: symfony-lab_nginx
        build:
            context: ./nginx
        container_name: symfony-lab_nginx
        depends_on:
            - php
        volumes:
            - ../public:/app/public
        ports:
            - '8000:80'
        networks:
            - aubesport_symfony-lab

    php:
        image: symfony-lab_php
        build:
            context: ./php
        container_name: symfony-lab_php
#        depends_on:
#            - mysql
        volumes:
            - ../:/app
        networks:
            - aubesport_symfony-lab
        working_dir: /app

    mysql:
        image: symfony-lab_mysql
        build:
            context: ./mysql
        container_name: symfony-lab_mysql
        volumes:
            - ./mysql/data:/var/lib/mysql
        ports:
            - '33060:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony-lab
            MYSQL_USER: user
            MYSQL_PASSWORD: aubesport
        networks:
            - aubesport_symfony-lab

networks:
    aubesport_symfony-lab: ~
