services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $targetDirectory: '%kernel.project_dir%/asset/images'
            $adminEmail: '%env(ADMIN_EMAIL)%'
            $noReplyEmail: '%env(NORENO_REPLY_EMAILPLY_EMAIL)%'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Kernel.php'
