services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $targetDirectory: '%images_directory%'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Kernel.php'

parameters:
    images_directory: '%kernel.project_dir%/asset/images'
