services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Image\ImageUploader:
        arguments:
            $targetDirectory: '%brochures_directory%'

parameters:
    brochures_directory: '%kernel.project_dir%/asset/uploads/images'
